package.json, start-helper.js, start.js
=> Project Setup

server/package-lock.json, server/package.json
=> Setting up basic server

server/.gitignore, server/server.js
=> Setting up the backend

.github/ISSUE_TEMPLATE/doc_report.yml
=> Changes are made in line no. 3

.github/ISSUE_TEMPLATE/feature_request.yml
=> changes are made in line no 3

server/.sample-env, server/README.md, server/app.js, server/controllers/questionsControllers.js, server/data/dev-data/import-and-delete-data-script.js, server/data/dev-data/questions.json, server/models/questionsModel.js, server/package-lock.json, server/package.json, server/routes/questionsRoutes.js, server/server.js
=> Backend Update (MVC Architecture, Base Routes, DB Connection, Scripts)

package.json, server/data/dev-data/questions.json
=> Sample questions

server/data/dev-data/answers.json
=> sample-answers 3

server/data/dev-data/questions.json
=>  Question no. 4 added.

server/controllers/answersControllers.js, server/data/dev-data/answers.json, server/data/dev-data/questions.json, server/routes/answersRoutes.js
=> Backend Update 3.0

server/.sample-env, server/app.js, server/controllers/answersControllers.js, server/controllers/authControllers.js, server/controllers/questionsControllers.js, server/controllers/usersControllers.js, server/models/usersModel.js, server/package-lock.json, server/package.json, server/routes/answersRoutes.js, server/routes/questionsRoutes.js, server/routes/usersRoutes.js
=> User authentication and routes added

.github/ISSUE_TEMPLATE/doc_report.yml, server/Dockerfile, server/README.md, server/cucumber.js, server/docker-compose.yml, server/package-lock.json, server/package.json, server/tests/features/support/steps.js, server/tests/features/test.feature, start.js
=> Minor bug fixes and API documentation

server/README.md
Inspiration section added.
#example
=> Updated readme

server/server.js
=> feat: :lock: Unhandled rejections and SIGTERM errors handled

server/data/dev-data/questions.json
=> Question no 11 added

server/data/dev-data/answers.json, server/data/dev-data/questions.json
=> Changes are made as per requirement.

client/src/components/App/App.js, client/src/components/Home/HomeRightContainer/HomeRightContainer.js
=> Updating right hand side section

client/src/components/Home/HomeRightContainer/HomeRightContainer.js
=> Building the contact card

client/src/components/Home/HomeCenterContainer/HomeCenterContainer.js, client/src/components/QACard/QACard.js, client/src/data/dev-data/questions.json
=> Wrapping up home page

client/package.json, client/src/components/Home/HomeCenterContainer/HomeCenterContainer.js, client/src/components/QACard/QACard.js, client/src/data/dev-data/questions.json, package-lock.json, package.json, server/models/usersModel.js, server/package-lock.json, server/package.json
=> Package updates and minor edits

Procfile
=> Procfile deployment update

server/server.js
=> feat: :hammer: Server closure update

package.json
=> feat: :package: Updated the install script
